version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    env_file: .env
    environment:
      RAILS_ENV: development
    networks:
      - backend
    labels:
      traefik.enable: "true"
      traefik.http.routers.app.entrypoints: "websecure"
      traefik.http.routers.app.rule: "Host(`${DEVISE_PASSKEYS_HOST}`)"
      traefik.http.routers.app.tls: "true"
      traefik.http.routers.app.tls.certresolver: "cloudflare"

volumes:
  gem_cache:

networks:
  backend:
    name: backend

